# Customer 360 Analytics

In [51]:
import pandas as pd 
import seaborn as sns
from pathlib import Path
from IPython.display import display
from datetime import datetime
from plotly.subplots import make_subplots
import plotly.graph_objects as go

## Assumption todays date 

#TODAYS_DATE = datetime.now()
TODAYS_DATE = datetime(2018, 10,18)

In [2]:
DATASET_FOLDER = Path.cwd() / "data_points"

## Data Loading and Initial Exploration

In [3]:
customers = pd.read_csv(DATASET_FOLDER / "customers.csv")
orders = pd.read_csv(DATASET_FOLDER / "orders.csv")
order_item = pd.read_csv(DATASET_FOLDER / "order_item.csv")
payments = pd.read_csv(DATASET_FOLDER / "payments.csv")
reviews = pd.read_csv(DATASET_FOLDER / "reviews.csv")
products = pd.read_csv(DATASET_FOLDER / "products.csv")
sellers = pd.read_csv(DATASET_FOLDER / "sellers.csv")
location = pd.read_csv(DATASET_FOLDER / "location.csv")
category_translation = pd.read_csv(DATASET_FOLDER / "category_translation.csv")

### Inspecting Stucture

### Customers

In [4]:
display(customers.head(2)) 
display(customers.info())

# There is no null value present 
# Customer unique id can be used to identify reapeat customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

None

### Orders

In [5]:
display(orders.head(2))
display(orders.info(), orders.describe())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

None

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-08-02 12:06:07,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [6]:
## Checking why order_approved_at is null 
orders[(orders.order_approved_at.isnull()) & (orders.order_status != 'canceled')]
## Null is present for delivered, creates status as well

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaN,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17 00:00:00
7434,b5359909123fa03c50bdb0cfed07f098,438449d4af8980d107bf04571413a8e7,created,2017-12-05 01:07:52,NaN,NaN,NaN,2018-01-11 00:00:00
9238,dba5062fbda3af4fb6c33b1e040ca38f,964a6df3d9bdf60fe3e7b8bb69ed893a,created,2018-02-09 17:21:04,NaN,NaN,NaN,2018-03-07 00:00:00
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaN,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21 00:00:00
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17 00:00:00
21441,7a4df5d8cff4090e541401a20a22bb80,725e9c75605414b21fd8c8d5a1c2f1d6,created,2017-11-25 11:10:33,NaN,NaN,NaN,2017-12-12 00:00:00
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaN,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31 00:00:00
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaN,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20 00:00:00
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01 00:00:00
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaN,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27 00:00:00
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaN,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22 00:00:00
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaN,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16 00:00:00
55086,35de4050331c6c644cddc86f4f2d0d64,4ee64f4bfc542546f422da0aeb462853,created,2017-12-05 01:07:58,NaN,NaN,NaN,2018-01-08 00:00:00
58958,90ab3e7d52544ec7bc3363c82689965f,7d61b9f4f216052ba664f22e9c504ef1,created,2017-11-06 13:12:34,NaN,NaN,NaN,2017-12-01 00:00:00
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20 00:00:00
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaN,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29 00:00:00
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21 00:00:00
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaN,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23 00:00:00
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaN,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31 00:00:00

In [7]:
## Checking why order_delivered_carrier_date is present for all delivered 
orders[(orders.order_delivered_carrier_date.isnull()) & (orders.order_status == 'delivered')]
# Null value present can be ignored only two entries are missing and we can safly drop these values

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
73222,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaN,2017-11-20 19:44:47,2017-11-14 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00

In [8]:
## Checking why order_delivered_customer_date is present for all delivered 
orders[(orders.order_delivered_customer_date.isnull()) & (orders.order_status == 'delivered')]
# There are 9 missinf entries we can delete this data even if the status is delivered date is not present this is and incomplete data entry.

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

### order item

In [9]:
display(order_item.head(2))
display(order_item.info(), order_item.describe())

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

None

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

### Payments

In [10]:
display(payments.head(3))
display(payments.info(), payments.describe())

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

None

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

### Reviews

In [11]:
display(reviews.head(2))
display(reviews.info(), reviews.describe())

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

None

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

### Secondary table

In [12]:
print("products".upper()); display(products.head(2)); display(products.info(), products.describe())
print("sellers".upper()); display(sellers.head(2)); display(sellers.info(), sellers.describe())
print("location".upper()); display(location.head(2)); display(location.info(), location.describe())
print("category_translation".upper()); display(category_translation.head()); display(category_translation.info(), category_translation.describe())

PRODUCTS

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

None

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

SELLERS

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

None

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

LOCATION

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

None

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

CATEGORY_TRANSLATION

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

None

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [13]:
display(products[products.product_category_name.isnull()])
# products.product_category_name.unique()
print(category_translation.product_category_name_english.str.lower().str.startswith("mis").sum())
## We have 610 product category that has null value need to replace this with Miscellaneous as the category is not present.

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

0

## Data Cleaning and Preprocessing

In [14]:
## Cleaning Orders
### droping duplicate data from all tables
customers = customers.drop_duplicates(keep="first")
orders = orders.drop_duplicates(keep="first")
order_item = order_item.drop_duplicates(keep="first")
payments = payments.drop_duplicates(keep="first")
reviews = reviews.drop_duplicates(keep="first")
products = products.drop_duplicates(keep="first")
sellers = sellers.drop_duplicates(keep="first")
location = location.drop_duplicates(keep="first")
category_translation = category_translation.drop_duplicates(keep="first")

### order_delivered_carrier_date and order_delivered_customer_date:  Null value present can be ignored as they are incomplete data
orders = orders.drop(orders[(orders.order_delivered_carrier_date.isnull()) & (orders.order_status == 'delivered')].index)
orders = orders.drop(orders[(orders.order_delivered_customer_date.isnull()) & (orders.order_status == 'delivered')].index)

### fixing data type
for x in ["order_purchase_timestamp", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"]:
    orders[x] = pd.to_datetime(orders[x], format="%Y-%m-%d %H:%M:%S")

In [15]:
## cleaning order_item

### handiling datatype
order_item["shipping_limit_date"] = pd.to_datetime(order_item["shipping_limit_date"], format="%Y-%m-%d %H:%M:%S")

In [16]:
## handling null product_category_name
products.product_category_name = products.product_category_name.fillna("Miscellaneous")

## Data Integration (Critical Component)

In [17]:
## Combined all the tables into one

### 1.  products + category_translation  ==>    products_f 
products_f = products.merge(category_translation, on=["product_category_name"], how="left")
products_f.loc[products_f.product_category_name=="Miscellaneous", "product_category_name_english"] = "Miscellaneous"
### 2.  order_items + products_f             ==>    order_item_1
order_item_1 = order_item.merge(products_f, on="product_id", how="left")
### 4.  order_items_1 + sellers                 ==>    order_item_f
order_item_f = order_item_1.merge(sellers, on="seller_id", how="left")
### 6.  orders + order_items _f                 ==>   orders_1    
orders_1 = orders.merge(order_item_f, on="order_id", how="left")               
### 7.  orders_1 + customers                    ==>   orders_2                   
orders_2 = orders_1.merge(customers, on="customer_id", how="left")
### 8.  orders_2 + payments                      ==>   orders_3
orders_3 = orders_2.merge(payments, on="order_id", how="left")
### 9.  orders_3+ reviews                           ==>   fact
fact = orders_3.merge(reviews, on="order_id", how="left")
fact

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,87285b34884572647811a353c7ac498a,...,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,87285b34884572647811a353c7ac498a,...,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,87285b34884572647811a353c7ac498a,...,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1.0,595fac2a385ac33a80bd5114aec74eb8,...,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1.0,aa4383b373c6aca5d8797843e5594415,...,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119129,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,1.0,credit_card,3.0,195.00,29bb71b2760d0f876dfa178a76bc4734,4.0,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01
119130,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1.0,b80910977a37536adeddd63663f916ad,...,1.0,credit_card,5.0,271.01,371579771219f6db2d830d50805977bb,5.0,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57
119131,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,1.0,credit_card,4.0,441.16,8ab6855b9fe9b812cd03a480a25058a1,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
119132,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,1.0,credit_card,4.0,441.16,8ab6855b9fe9b812cd03a480a25058a1,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
119133,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1.0,006619bbed68b000c8ba3f8725d5409e,...,1.0,debit_card,1.0,86.86,dc9c59b4688062c25758c2be4cafc523,5.0,NaN,NaN,2018-03-17 00:00:00,2018-03-17 16:33:31

In [18]:
display(fact.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119134 entries, 0 to 119133
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119134 non-null  object
 1   customer_id                    119134 non-null  object
 2   order_status                   119134 non-null  object
 3   order_purchase_timestamp       119134 non-null  datetime64[ns]
 4   order_approved_at              118957 non-null  datetime64[ns]
 5   order_delivered_carrier_date   117050 non-null  datetime64[ns]
 6   order_delivered_customer_date  115721 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119134 non-null  datetime64[ns]
 8   order_item_id                  118301 non-null  float64
 9   product_id                     118301 non-null  object
 10  seller_id                      118301 non-null  object
 11  shipping_limit_date            118301 non-null  datetime64[ns]
 12  price                          118301 non-null  float64
 13  freight_value                  118301 non-null  float64
 14  product_category_name          118301 non-null  object
 15  product_name_lenght            116592 non-null  float64
 16  product_description_lenght     116592 non-null  float64
 17  product_photos_qty             116592 non-null  float64
 18  product_weight_g               118281 non-null  float64
 19  product_length_cm              118281 non-null  float64
 20  product_height_cm              118281 non-null  float64
 21  product_width_cm               118281 non-null  float64
 22  product_category_name_english  118276 non-null  object
 23  seller_zip_code_prefix         118301 non-null  float64
 24  seller_city                    118301 non-null  object
 25  seller_state                   118301 non-null  object
 26  customer_unique_id             119134 non-null  object
 27  customer_zip_code_prefix       119134 non-null  int64
 28  customer_city                  119134 non-null  object
 29  customer_state                 119134 non-null  object
 30  payment_sequential             119131 non-null  float64
 31  payment_type                   119131 non-null  object
 32  payment_installments           119131 non-null  float64
 33  payment_value                  119131 non-null  float64
 34  review_id                      118137 non-null  object
 35  review_score                   118137 non-null  float64
 36  review_comment_title           13985 non-null   object
 37  review_comment_message         50240 non-null   object
 38  review_creation_date           118137 non-null  object
 39  review_answer_timestamp        118137 non-null  object
dtypes: datetime64[ns](6), float64(15), int64(1), object(18)
memory usage: 36.4+ MB

None

In [19]:
fact.where(fact.order_status=="delivered").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119134 entries, 0 to 119133
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115714 non-null  object
 1   customer_id                    115714 non-null  object
 2   order_status                   115714 non-null  object
 3   order_purchase_timestamp       115714 non-null  datetime64[ns]
 4   order_approved_at              115699 non-null  datetime64[ns]
 5   order_delivered_carrier_date   115714 non-null  datetime64[ns]
 6   order_delivered_customer_date  115714 non-null  datetime64[ns]
 7   order_estimated_delivery_date  115714 non-null  datetime64[ns]
 8   order_item_id                  115714 non-null  float64
 9   product_id                     115714 non-null  object
 10  seller_id                      115714 non-null  object
 11  shipping_limit_date            115714 non-null  datetime64[ns]
 12  price                          115714 non-null  float64
 13  freight_value                  115714 non-null  float64
 14  product_category_name          115714 non-null  object
 15  product_name_lenght            114076 non-null  float64
 16  product_description_lenght     114076 non-null  float64
 17  product_photos_qty             114076 non-null  float64
 18  product_weight_g               115694 non-null  float64
 19  product_length_cm              115694 non-null  float64
 20  product_height_cm              115694 non-null  float64
 21  product_width_cm               115694 non-null  float64
 22  product_category_name_english  115691 non-null  object
 23  seller_zip_code_prefix         115714 non-null  float64
 24  seller_city                    115714 non-null  object
 25  seller_state                   115714 non-null  object
 26  customer_unique_id             115714 non-null  object
 27  customer_zip_code_prefix       115714 non-null  float64
 28  customer_city                  115714 non-null  object
 29  customer_state                 115714 non-null  object
 30  payment_sequential             115711 non-null  float64
 31  payment_type                   115711 non-null  object
 32  payment_installments           115711 non-null  float64
 33  payment_value                  115711 non-null  float64
 34  review_id                      114853 non-null  object
 35  review_score                   114853 non-null  float64
 36  review_comment_title           13580 non-null   object
 37  review_comment_message         48090 non-null   object
 38  review_creation_date           114853 non-null  object
 39  review_answer_timestamp        114853 non-null  object
dtypes: datetime64[ns](6), float64(16), object(18)
memory usage: 36.4+ MB

In [20]:
fact.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm',
       'product_category_name_english', 'seller_zip_code_prefix',
       'seller_city', 'seller_state', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

## Feature Engineering

### 1. Core Transactional (RFM) Features
- **Recency:** `Current_Date - max(order_purchase_timestamp)`. (How fresh is the customer?)
- **Frequency:** `count(distinct order_id)`. (How loyal are they?)
- **Monetary (LTV):** `sum(payment_value)`. (How valuable are they?)
- **Average Ticket Size:** `sum(payment_value) / count(distinct order_id)`.
- **Time-to-Next-Purchase:** `max(order_purchase_timestamp) - min(order_purchase_timestamp)/ count(distinct order_id)`

In [82]:
RFM_features = fact.groupby("customer_unique_id").agg(
    RecentOrders=("order_purchase_timestamp", lambda x: x.max()), 
    FrequenyOrders=("order_id", lambda x: x.nunique()),
    LTV=("payment_value", lambda x:x.sum()),
    OldestOrder=("order_purchase_timestamp", lambda x: x.min())
)
RFM_features["Recency"] =(TODAYS_DATE - RFM_features.RecentOrders).dt.days
RFM_features['AverageTicketSize'] = RFM_features.LTV / RFM_features.FrequenyOrders
RFM_features["TimetoNextPurchase"] = ((RFM_features.RecentOrders - RFM_features.OldestOrder).dt.days / (RFM_features.FrequenyOrders - 1))
RFM_features

,RecentOrders,FrequenyOrders,LTV,OldestOrder,Recency,AverageTicketSize,TimetoNextPurchase
customer_unique_id,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,1,141.90,2018-05-10 10:56:27,160,141.90,NaN
0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,1,27.19,2018-05-07 11:11:27,163,27.19,NaN
0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,1,86.22,2017-03-10 21:05:03,586,86.22,NaN
0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,1,43.62,2017-10-12 20:29:41,370,43.62,NaN
0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,1,196.89,2017-11-14 19:45:42,337,196.89,NaN
...,...,...,...,...,...,...,...
fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,1,4134.84,2017-06-08 21:00:36,496,4134.84,NaN
fffea47cd6d3cc0a88bd621562a9d061,2017-12-10 20:07:56,1,84.58,2017-12-10 20:07:56,311,84.58,NaN
ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,1,112.46,2017-02-07 15:49:16,617,112.46,NaN
ffff5962728ec6157033ef9805bacc48,2018-05-02 15:17:41,1,133.69,2018-05-02 15:17:41,168,133.69,NaN
ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,1,71.56,2017-05-02 20:18:45,533,71.56,NaN

### 2. Logistic & Experience Features

*Source: `order_delivered_customer_date`, `order_estimated_delivery_date`, `review_score`*

- **Delivery Delay:** `order_delivered_customer_date - order_estimated_delivery_date`. (Positive values indicate late deliveries, a primary churn driver).
- **Lead time**: `order_delivered_customer_date - order_purchase_timestamp`
- **Average Review Score:** `mean(review_score)`. (A direct proxy for customer satisfaction).
- **Review Propensity:** `count(review_id) / count(order_id)`. (Does this customer engage with the feedback loop?).
- **Freight Ratio:** `sum(freight_value) / sum(payment_value)`. (High ratios often lead to cart abandonment in the future).

In [30]:
fact["del_delay"] = (fact.order_delivered_customer_date - fact.order_estimated_delivery_date).dt.days
fact["lead time"] = (fact.order_delivered_customer_date - fact.order_purchase_timestamp).dt.days
print("Average Review score", fact.review_score.mean())
print("Review Propensity", fact.review_id.nunique() / fact.order_id.nunique())
print("Freight Ratio", fact.freight_value.sum() / fact.payment_value.sum())

Average Review score 4.015541278346327
Review Propensity 0.9896311046745514
Freight Ratio 0.11516553782038337

## 3. Product & Diversity Features

*Source: `product_category_name_english`, `product_id`, `payment_type`*

- **Category Affinity:** The `mode` or most frequent `product_category_name_english`.
- **Breadth of Interest:** `count(distinct product_category_name_english)`. (Does the customer only buy electronics, or do they explore?).
- **Installment User:** `mean(payment_installments)`. (High installments often indicate high-value, price-sensitive shoppers).
- **Preferred Payment Method:** `mode(payment_type)`. (Credit card vs. boleto/voucher).

In [39]:
print("Category Affinity:", fact.product_category_name_english.mode()[0])
print("Breadth of Interest:", fact.product_category_name_english.nunique())
print("Installment User:", fact.payment_installments.mean())
print("Preferred Payment Method:", fact.payment_type.mode()[0])

Category Affinity: bed_bath_table
Breadth of Interest: 72
Installment User: 2.9412747311782828
Preferred Payment Method: credit_card

### 4. Geographic & Seller Relationship

*Source: `customer_state`, `seller_id`, `product_weight_g`*

- **Seller Loyalty:** `count(distinct seller_id) / count(order_id)`. (A low ratio means they keep returning to the same sellers).
- **Heavy Goods Buyer:** `mean(product_weight_g)`. (Useful for shipping-related promotions).

In [ ]:
print("Seller loyalty", fact.seller_id.nunique() / fact.order_id.nunique())
print("Heavy Goods Buyer(gms):", fact.product_weight_g.mean())

Seller loyalty 0.03112680022527959
Heavy Goods Buyer: 2112.217389098841

## Exploratory Data Analysis (EDA)

### Customer Analysis
- Repeat Purchase Rate: (Number of Repeat Customers / Total Customers)
- Time-to-Next-Purchase (TTNP)

In [70]:
# 1. Define the grid and EXPLICITLY set the types to 'indicator'
fig = make_subplots(
    rows=1, cols=2,
    specs=[[{"type": "indicator"}, {"type": "indicator"}]],
    subplot_titles=("Repeat Purchase Rate", "Time-to-Next-Purchase")
)

# 2. Add the first indicator
fig.add_trace(
    go.Indicator(
        mode = "number",
        value = (RFM_features.FrequenyOrders>1).sum()/ len(RFM_features.index) * 100,
        title = {"text": "Repeat Purchase Rate (%)"},
    ),
    row=1, col=1
)

# 3. Add the second indicator (Placeholder for Time-to-Next-Purchase)
fig.add_trace(
    go.Indicator(
        mode = "number",
        value = RFM_features.TimetoNextPurchase.mean(), # Replace with your calculation
        title = {"text": "Avg Days to Reorder"},
    ),
    row=1, col=2
)

fig.update_layout(
    height=400, 
    paper_bgcolor = "lightgray", 
    title={
        "text": "Customer Analysis",
        'y': 0.93,        # Vertical position (0 to 1)
        'x': 0.5,         # Horizontal position (0.5 is centered)
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {'size': 32, 'family': "Arial"}
        }
    )
fig.show()

In [84]:
# 1. Define the grid - both are now 'xy' because both are Histograms
fig = make_subplots(
    rows=1, cols=2,
    specs=[[{"type": "xy"}, {"type": "xy"}]], 
    subplot_titles=("Recency Distribution", "Time-to-Next-Purchase Distribution")
)

# 2. Add the first Histogram (Recency)
fig.add_trace(
    go.Histogram(
        x=RFM_features.Recency,
        name="Recency",
        marker_color='#636EFA',
        nbinsx=50
    ),
    row=1, col=1
)

# 3. Add the second Histogram (Time to Next Purchase)
fig.add_trace(
    go.Histogram(
        x=RFM_features.TimetoNextPurchase,
        name="Days to Reorder",
        marker_color='#EF553B', # Different color for contrast
        nbinsx=50
    ),
    row=1, col=2
)

# 4. Update Layout
fig.update_layout(
    height=500, 
    template="plotly_white", # Cleaner look for EDA
    title={
        "text": "Customer Behavioral Distributions",
        'y': 0.95, 'x': 0.5,
        'xanchor': 'center', 'yanchor': 'top',
        'font': {'size': 24}
    },
    margin=dict(t=100)
)

# Optional: Add axis titles
fig.update_xaxes(title_text="Days since last purchase", row=1, col=1)
fig.update_xaxes(title_text="Days between purchases", row=1, col=2)

fig.show()

In [ ]:
go

Histogram({
    'x': array([141.9 ,  27.19,  86.22, ..., 112.46, 133.69,  71.56],
         shape=(96087,))
})